In [4]:
import os
os.getenv('path')

'c:\\ProgramData\\anaconda3\\envs\\lzhcsi;C:\\ProgramData\\anaconda3\\envs\\lzhcsi;C:\\ProgramData\\anaconda3\\envs\\lzhcsi\\Library\\mingw-w64\\bin;C:\\ProgramData\\anaconda3\\envs\\lzhcsi\\Library\\usr\\bin;C:\\ProgramData\\anaconda3\\envs\\lzhcsi\\Library\\bin;C:\\ProgramData\\anaconda3\\envs\\lzhcsi\\Scripts;C:\\ProgramData\\anaconda3\\envs\\lzhcsi\\bin;C:\\ProgramData\\anaconda3\\condabin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\libnvvp;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\ProgramData\\anaconda3\\Scripts;C:\\ProgramData\\anaconda3;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.2.1;C:\\Users\\user1\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2023.1\\bin;C:\\Users\\user1\

In [ ]:
print("hello world!")
a = 1
a


hello world!


1

In [5]:
print(os.environ['path'])


c:\ProgramData\anaconda3\envs\lzhcsi;C:\ProgramData\anaconda3\envs\lzhcsi;C:\ProgramData\anaconda3\envs\lzhcsi\Library\mingw-w64\bin;C:\ProgramData\anaconda3\envs\lzhcsi\Library\usr\bin;C:\ProgramData\anaconda3\envs\lzhcsi\Library\bin;C:\ProgramData\anaconda3\envs\lzhcsi\Scripts;C:\ProgramData\anaconda3\envs\lzhcsi\bin;C:\ProgramData\anaconda3\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\anaconda3\Scripts;C:\ProgramData\anaconda3;C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.2.1;C:\Users\user1\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2023.1\bin;C:\Users\user1\AppData\Local\Programs\Microsoft VS Code\bin


In [7]:
from datetime import datetime
import os
current_time = datetime.now().strftime('%b%d_%H-%M-%S')
name =  'csi_prediction'
comment = ''
checkpoint_path = 'checkpoints'
file_name = os.path.join(
            name + '_' + current_time + '_' + comment)


In [8]:
'%s/%s' % (checkpoint_path, file_name)

'checkpoints/csi_prediction_Oct04_18-49-03_'

In [3]:
import GPUtil
deviceIDs = GPUtil.getAvailable(order = 'memory', limit = 1, maxLoad=0.5, maxMemory=0.5)
gpuInfo = GPUtil.getGPUs()[deviceIDs[0]]

In [7]:
deviceIDs

[0]

In [6]:
print("GPU使用情况:")
print("ID:",gpuInfo.id)
print("名称:",gpuInfo.name)
print("内存使用:",gpuInfo.memoryUsed)
print("内存总量:",gpuInfo.memoryTotal)
print("使用率:",gpuInfo.load)

GPU使用情况:
ID: 0
名称: NVIDIA A100-PCIE-40GB
内存使用: 14.0
内存总量: 40960.0
使用率: 0.0


In [ ]:
a  = 2

In [9]:
a = 3

In [10]:
a

3

In [ ]:
import os
repo_name='dressing-in-order'
os.chdir(f'./{repo_name}')

AnnotatedTransformer.ipynb  tempo_test.py	 test_environment.py
tempo_test.ipynb	    tensorboard_test.py  the_annotated_transformer.py


In [19]:
import torch
data = torch.randint(0,10,(2, 10))


In [20]:
data

tensor([[7, 2, 7, 9, 2, 6, 4, 6, 8, 8],
        [1, 7, 2, 2, 1, 8, 0, 9, 8, 5]])

In [ ]:
import torch
N = 36
q_len = 10
k_len = 10
# q_len = Q.size(1)  Q:(batch_size, seq_len, num_heads, d_k)
num_heads = 8
attn_mask = torch.randint(0, 10, (N, q_len, k_len))
attn_mask.shape

torch.Size([36, 10, 10])

In [25]:
attn_mask = attn_mask.unsqueeze(1).repeat(1, num_heads, 1, 1)    # broadcast
attn_mask.shape

torch.Size([36, 8, 10, 10])

In [26]:
attn_mask = attn_mask.bool()
attn_mask.shape

torch.Size([36, 8, 10, 10])

In [37]:
size = 10    
"Mask out subsequent positions."
attn_shape = (1, size, size)
subsequent_mask = torch.triu(torch.ones(attn_shape), diagonal=1).type(
    torch.uint8
)
subsequent_mask == 0

tensor([[[ True, False, False, False, False, False, False, False, False, False],
         [ True,  True, False, False, False, False, False, False, False, False],
         [ True,  True,  True, False, False, False, False, False, False, False],
         [ True,  True,  True,  True, False, False, False, False, False, False],
         [ True,  True,  True,  True,  True, False, False, False, False, False],
         [ True,  True,  True,  True,  True,  True, False, False, False, False],
         [ True,  True,  True,  True,  True,  True,  True, False, False, False],
         [ True,  True,  True,  True,  True,  True,  True,  True, False, False],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True, False],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True]]])

In [36]:
torch.ones(attn_shape)

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [22]:
import h5py
import numpy as np
import torch
a = '/data/lzh/Umi_outdoor30_1_6_11_16(5).mat'
csi = h5py.File(a, 'r')
csi = csi[list(csi.keys())[0]]
print(type(csi))
print(csi.shape)
csi = np.array(csi)
csi = np.transpose((5,4,3,2,1,0))
print(csi.shape)

<class 'h5py._hl.dataset.Dataset'>
(2, 2, 32, 12, 4, 114000)
(6,)


In [23]:
csi = torch.from_numpy(csi).float()
csi = csi.permute(5,4,3,2,1,0)


RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 1 is not equal to len(dims) = 6

In [ ]:
csi.shape

torch.Size([114000, 4, 12, 32, 2, 2])